
name: Terraform CI

on:
  pull_request:
    paths: ["infra/**", "modules/**"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        run: terraform -chdir=infra fmt -check
      - name: Terraform init & plan
        run: |
          terraform -chdir=infra init -backend=false
          terraform -chdir=infra plan -input=false
